caffe/caffe/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import index_navigate, caffe_create

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', index_navigate, name='index_navigate'),
    url(r'^create/$', caffe_create, name='caffe_create'),

    url(r'cafe/', include('home.urls', namespace='home')),
    url(r'reports/', include('reports.urls', namespace='reports')),
    url(r'stencils/', include('stencils.urls', namespace='stencils')),
    url(r'employees/', include('employees.urls', namespace='employees')),
    url(r'statistics/', include('stats.urls', namespace='statistics')),
    url(r'calendar/', include('calendars.urls', namespace='calendar')),
    url(r'hours/', include('hours.urls', namespace='hours')),
    url(r'cash/', include('cash.urls', namespace='cash')),
]

caffe/cash/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (cash_edit_cash_report, cash_edit_company,
                    cash_edit_expense, cash_navigate, cash_new_cash_report,
                    cash_new_company, cash_new_expense,
                    cash_show_cash_report)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', cash_navigate, name='navigate'),
    url(r'^(?P<report_id>\d{0,17})/$', cash_show_cash_report, name='show'),
    url(r'^new/$', cash_new_cash_report, name='new'),
    url(
        r'^edit/(?P<report_id>\d{0,17})/$',
        cash_edit_cash_report,
        name='edit'
    ),

    url(r'^new/company/$', cash_new_company, name='new_company'),
    url(
        r'^edit/company/(?P<company_id>\d{0,17})/$',
        cash_edit_company,
        name='edit_company'
    ),

    url(r'^new/expense/$', cash_new_expense, name='new_expense'),
    url(r'^edit/expense/(?P<expense_id>\d{0,17})/$',
        cash_edit_expense, name='edit_expense'),
]

caffe/employees/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from employees.views import (employees_delete_employee,
                             employees_edit_employee,
                             employees_logout_employee, employees_navigate,
                             employees_new_employee,
                             employees_show_all_employees)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', employees_navigate, name='navigate'),

    url(r'^all/$', employees_show_all_employees, name='all'),
    url(r'^new/$', employees_new_employee, name='new'),
    url(
        r'^edit/(?P<employee_id>\d{0,17})/$',
        employees_edit_employee,
        name='edit'
    ),
    url(
        r'^delete/(?P<employee_id>\d{0,17})/$',
        employees_delete_employee,
        name='delete'
    ),

    url(
        r'^login/$', auth_views.login,
        {'template_name': 'employees/login.html'},
        name='login'
    ),
    url(r'^logout/$', employees_logout_employee, name='logout'),
]

caffe/employees/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Employee(AbstractUser):
    """Employee model, extends AbstractUser fields."""

    telephone_number = models.CharField(max_length=20, blank=True)
    favorite_coffee = models.CharField(max_length=50, blank=True)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('last_name', 'first_name',)
        default_permissions = ('add', 'change', 'delete', 'view')

caffe/employees/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group

from .models import Employee


class EmployeeForm(UserCreationForm):
    """Responsible for proper saving Employee form."""

    email = forms.EmailField()

    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Employee
        fields = (
            'username',
            'first_name',
            'last_name',
            'groups',
            'telephone_number',
            'email',
            'favorite_coffee'
        )

    def __init__(self, *args, **kwargs):
        """Init form data."""

        kwargs.setdefault('label_suffix', '')  # removes ":" from labels

        self.caffe = kwargs.pop('caffe')

        super(EmployeeForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = 'Nazwa użytkownika'
        self.fields['first_name'].label = 'Imię'
        self.fields['last_name'].label = 'Nazwisko'
        self.fields['telephone_number'].label = 'Numer telefonu'
        self.fields['email'].label = 'Adres email'
        self.fields['favorite_coffee'].label = 'Twoja ulubiona kawa?'
        self.fields['groups'].label = 'Grupy uprawnień użytkownika'

        self.fields['groups'].queryset |= Group.objects.all()

        if self.instance:
            self.initial['username'] = self.instance.username
            self.initial['first_name'] = self.instance.first_name
            self.initial['last_name'] = self.instance.last_name
            self.initial['telephone_number'] = self.instance.telephone_number
            self.initial['email'] = self.instance.email
            self.initial['favorite_coffee'] = self.instance.favorite_coffee

            try:
                self.initial['groups'] = self.instance.group.get()
            except AttributeError:
                pass

    def save(self, commit=True):
        """Override of save method, to add users groups."""

        employee = super(EmployeeForm, self).save(commit=False)
        employee.caffe = self.caffe
        if commit:
            employee.save()

            try:
                employee.groups.clear()
            except AttributeError:
                pass

            # add groups to user
            for group in self.cleaned_data['groups']:
                employee.groups.add(group)

        return employee

caffe/employees/views.py
"""Module with views for the employee feature."""

from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import EmployeeForm
from .models import Employee


@login_required
def employees_logout_employee(request):
    """Logout a user, default behaviour."""

    logout(request)
    return render(request, 'employees/logout.html')


@permission_required('employees.add_employee')
def employees_new_employee(request):
    """Create a new employee."""

    form = EmployeeForm(request.POST or None, caffe=request.user.caffe)

    if form.is_valid():
        form.save()
        messages.success(request, 'Pracownik został poprawnie stworzony.')
        return redirect(reverse('employees:navigate'))
    elif request.POST:
        messages.error(request, u'Formularz został niepoprawnie wypełniony.')

    return render(request, 'employees/new.html', {
        'form': form
    })


@permission_required('employees.change_employee')
def employees_edit_employee(request, employee_id):
    """Edit an employee."""

    employee = get_object_or_404(
        Employee,
        id=employee_id,
        caffe=request.user.caffe
    )

    form = EmployeeForm(
        request.POST or None,
        instance=employee,
        caffe=request.user.caffe
    )

    if form.is_valid():
        form.save()
        messages.success(request, 'Pracownik został poprawnie zmieniony.')
        return redirect(reverse('employees:navigate'))
    elif request.POST:
        messages.error(request, u'Formularz został niepoprawnie wypełniony.')

    return render(request, 'employees/edit.html', {
        'form': form,
        'employee': employee
    })


@permission_required('employees.delete_employee')
def employees_delete_employee(request, employee_id):
    """Delete an employee."""

    employee = get_object_or_404(
        Employee,
        id=employee_id,
        caffe=request.user.caffe
    )

    if employee == request.user:
        messages.error(request, u'Nie możesz usunąć siebie.')
        return redirect(reverse('employees:navigate'))

    employee.delete()
    messages.success(request, u'Pracownik został poprawnie usunięty.')
    return redirect(reverse('employees:navigate'))


@permission_required('employees.view_employee')
def employees_show_all_employees(request):
    """Show all employees."""

    employees = Employee.objects.filter(caffe=request.user.caffe).all()

    return render(request, 'employees/all.html', {
        'employees': employees
    })


@permission_required('employees.view_employee')
def employees_navigate(request):
    """Show main employee page."""

    return render(request, 'home/employees.html')

caffe/templates/employees/all.html
{% extends "home/base.html" %}

{% block title %}
  Wszyscy pracownicy
{% endblock %}

{% block content %}
<table class="table--hover table--shadow">
  <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Email</th>
      <th>Numer telefonu</th>
      {% if perms.employees.change_employee %}
        <th class="center">Edytuj</th>
      {% endif %}
      {% if perms.employees.delete_employee %}
        <th class="center">Usuń</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
      <tr>
        <td>{{ employee.first_name }}</td>
        <td>{{ employee.last_name }}</td>
        <td>{{ employee.email }}</td>
        <td>{{ employee.telephone_number }}</td>
        {% if perms.employees.change_employee %}
          <td class="table__cell--center icon icon__edit"><a href="{% url 'employees:edit' employee.id %}"><i class="fa fa-pencil"></i></a></td>
        {% endif %}
        {% if perms.employees.delete_employee %}
          <td class="table__cell--center icon icon__delete"><a href="{% url 'employees:delete' employee.id %}" onclick="return confirm('Czy na pewno chcesz usunąć tego pracownika?');"><i class="fa fa-trash"></i></a></td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

caffe/templates/employees/edit.html
{% extends "home/base.html" %}
{% load tags %}

{% block title %}
  Edytuj pracownika
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  <div class="input-line">
    {{ form.first_name }}
    {{ form.first_name.label_tag }}
  </div>
  {{ form.first_name.errors }}

  <div class="input-line">
    {{ form.last_name }}
    {{ form.last_name.label_tag }}
  </div>
  {{ form.last_name.errors }}

  <div class="input-line">
    {{ form.telephone_number }}
    {{ form.telephone_number.label_tag }}
  </div>
  {{ form.telephone_number.errors }}

  <div class="input-line">
    {{ form.email }}
    {{ form.email.label_tag }}
  </div>
  {{ form.email.errors }}

  <div class="input-line">
    {{ form.groups }}
    {{ form.groups.label_tag }}
  </div>
  {{ form.groups.errors }}

  <div class="input-line">
    {{ form.favorite_coffee }}
    {{ form.favorite_coffee.label_tag }}
  </div>
  {{ form.favorite_coffee.errors }}

  <hr/>

  <div class="input-line">
    {{ form.username }}
    {{ form.username.label_tag }}
  </div>
  {{ form.username.errors }}

  <div class="input-line">
    {{ form.password1 }}
    {{ form.password1.label_tag }}
  </div>
  {{ form.password1.errors }}

  <div class="input-line">
    {{ form.password2 }}
    {{ form.password2.label_tag }}
  </div>
  {{ form.password2.errors }}

  <button type="submit" class="button button-rounded button-green">Uaktualnij</button>
</form>
{% endblock %}

caffe/templates/employees/login.html
{% extends "home/landing_page.html" %}

{% block content %}
<div class="title">
  Logowanie
</div>

{% if messages %}
  <div class="alerts">
    {% for message in messages %}
      <div class="alert alert-rounded {{ message.tags }}">{{ message }}</div>
    {% endfor %}
  </div>
{% endif %}

<form method="post" class="element-form">
  <input type="hidden" name="next" value="{% url 'home:navigate' %}" />
  {% csrf_token %}

  <div class="input-line">
    {{ form.username }}
    {{ form.username.label_tag }}
  </div>
  {{ form.username.errors }}

  <div class="input-line">
    {{ form.password }}
    {{ form.password.label_tag }}
  </div>
  {{ form.password.errors }}

  <button type="submit" class="button button-rounded button-green">Zaloguj</button>
</form>
{% endblock %}

caffe/templates/employees/logout.html
{% extends "home/landing_page.html" %}

{% block content %}
<script>
(function ($) {
  "use strict"

  $(document).ready(function() {
    console.log(window.location);
    setTimeout(function() {
      window.location.replace(window.location.origin);
    }, 3000);
  });
})(jQuery);
</script>

<div class="title">
  Wylogowanie
</div>

<div class="alert alert-rounded alert-green">
  Zostałeś poprawnie wylogowany.
</div>
{% endblock %}

caffe/templates/employees/new.html
{% extends "home/base.html" %}
{% load tags %}

{% block title %}
  Nowy pracownik
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  <div class="input-line">
    {{ form.first_name }}
    {{ form.first_name.label_tag }}
  </div>
  {{ form.first_name.errors }}

  <div class="input-line">
    {{ form.last_name }}
    {{ form.last_name.label_tag }}
  </div>
  {{ form.last_name.errors }}

  <div class="input-line">
    {{ form.telephone_number }}
    {{ form.telephone_number.label_tag }}
  </div>
  {{ form.telephone_number.errors }}

  <div class="input-line">
    {{ form.email }}
    {{ form.email.label_tag }}
  </div>
  {{ form.email.errors }}
  
  <div class="input-line">
    {{ form.groups }}
    {{ form.groups.label_tag }}
  </div>
  {{ form.groups.errors }}

  <div class="input-line">
    {{ form.favorite_coffee }}
    {{ form.favorite_coffee.label_tag }}
  </div>
  {{ form.favorite_coffee.errors }}

  <hr/>

  <div class="input-line">
    {{ form.username }}
    {{ form.username.label_tag }}
  </div>
  {{ form.username.errors }}

  <div class="input-line">
    {{ form.password1 }}
    {{ form.password1.label_tag }}
  </div>
  {{ form.password1.errors }}

  <div class="input-line">
    {{ form.password2 }}
    {{ form.password2.label_tag }}
  </div>
  {{ form.password2.errors }}

  <button type="submit" class="button button-rounded button-green">Dodaj</button>
</form>
{% endblock %}