caffe/caffe/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import index_navigate, caffe_create

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', index_navigate, name='index_navigate'),
    url(r'^create/$', caffe_create, name='caffe_create'),

    url(r'cafe/', include('home.urls', namespace='home')),
    url(r'reports/', include('reports.urls', namespace='reports')),
    url(r'stencils/', include('stencils.urls', namespace='stencils')),
    url(r'employees/', include('employees.urls', namespace='employees')),
    url(r'statistics/', include('stats.urls', namespace='statistics')),
    url(r'calendar/', include('calendars.urls', namespace='calendar')),
    url(r'hours/', include('hours.urls', namespace='hours')),
    url(r'cash/', include('cash.urls', namespace='cash')),
]

caffe/cash/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (cash_edit_cash_report, cash_edit_company,
                    cash_edit_expense, cash_navigate, cash_new_cash_report,
                    cash_new_company, cash_new_expense,
                    cash_show_cash_report)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', cash_navigate, name='navigate'),
    url(r'^(?P<report_id>\d{0,17})/$', cash_show_cash_report, name='show'),
    url(r'^new/$', cash_new_cash_report, name='new'),
    url(
        r'^edit/(?P<report_id>\d{0,17})/$',
        cash_edit_cash_report,
        name='edit'
    ),

    url(r'^new/company/$', cash_new_company, name='new_company'),
    url(
        r'^edit/company/(?P<company_id>\d{0,17})/$',
        cash_edit_company,
        name='edit_company'
    ),

    url(r'^new/expense/$', cash_new_expense, name='new_expense'),
    url(r'^edit/expense/(?P<expense_id>\d{0,17})/$',
        cash_edit_expense, name='edit_expense'),
]

caffe/cash/models.py
"""Module with all models related to cash reports."""

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.utils.translation import ugettext_lazy as _


class Company(models.Model):
    """Stores one company a cafe interacts with (e.g., GoodCake bakery)."""

    name = models.CharField(max_length=200)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        self.full_clean()
        super(Company, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class Expense(models.Model):
    """Represents an object a cafe pays for during the day (e.g., cakes).

    One entry could look like this:
    (name: cakes, company: GoodCake) or
    (name: newspapers).
    """

    name = models.CharField(max_length=300)
    company = models.ForeignKey('Company', blank=True, null=True)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name', 'company')
        default_permissions = ('add', 'change', 'delete', 'view')

    def clean(self, *args, **kwargs):
        """Clean data and check validation."""

        # checks if there exists two products with same name
        query = Expense.objects.filter(name=self.name, caffe=self.caffe)
        if self.pk:
            query = query.exclude(pk=self.pk)

        if query.exists():
            raise ValidationError(
                _('Wydatek powinien mieć unikalną nazwę.')
            )

        super(Expense, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.company:
            if self.caffe != self.company.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia firmy nie zgadza się.')
                )

        self.full_clean()
        super(Expense, self).save(*args, **kwargs)

    def __str__(self):
        return '{}, {}'.format(self.name, self.company)


class FullExpense(models.Model):
    """Stores one specific expense - expense and amount.

    Is assigned to one report and can't be reused.
    """

    expense = models.ForeignKey('Expense')
    amount = models.FloatField()
    cash_report = models.ForeignKey(
        'CashReport',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='full_expenses'
    )
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        default_permissions = ('add', 'change', 'delete', 'view')

    def clean(self, *args, **kwargs):
        """Clean data and check validation."""

        # checks if there exists two same expenses
        full_expenses = []
        if self.cash_report is not None:
            full_expenses = self.cash_report.full_expenses.all()

        for full_expense in full_expenses:
            if full_expense.expense == self.expense:
                raise ValidationError(
                    _('Cash Report should not contain two same expenses.')
                )

        super(FullExpense, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.cash_report:
            if self.caffe != self.cash_report.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia raportu z kasy nie zgadza się.')
                )

        if self.caffe != self.expense.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia wydatku nie zgadza się.')
            )

        self.full_clean()
        super(FullExpense, self).save(*args, **kwargs)

    def __str__(self):
        return '{}: {}'.format(self.expense, self.amount)


class CashReport(models.Model):
    """Stores a single report representing money flow during one shift."""

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey('employees.Employee')
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    cash_before_shift = models.FloatField()
    cash_after_shift = models.FloatField()
    card_payments = models.FloatField()
    amount_due = models.FloatField()

    class Meta:
        ordering = ('-created_on', '-updated_on')
        default_permissions = ('add', 'change', 'delete', 'view')

    def balance(self):
        """Calculate balance within one report, indicate deficit/surplus."""

        expenses = 0
        if self.full_expenses.count() > 0:
            expenses = (
                self.full_expenses.aggregate(Sum('amount'))['amount__sum']
            )

        return (self.cash_after_shift + self.card_payments + expenses - \
                self.cash_before_shift - self.amount_due)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.creator is not None:
            if self.caffe != self.creator.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia tworzącego powinna się zgadzać')
                )

        self.full_clean()
        super(CashReport, self).save(*args, **kwargs)

    def __str__(self):
        return 'Report created: {:%Y-%m-%d %H:%M} by {}'.format(
            self.created_on,
            self.creator
        )

caffe/cash/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CashReportForm, CompanyForm, ExpenseForm, FullExpenseForm
from .models import CashReport, Company, Expense, FullExpense


@permission_required('cash.add_company')
def cash_new_company(request):
    """Show form to create new Company and show existing Companies."""

    elements = []

    form = CompanyForm(request.POST or None, caffe=request.user.caffe)

    if form.is_valid():
        form.save()
        messages.success(request, 'Firma została poprawnie dodana.')
        return redirect(reverse('cash:navigate'))

    companies = Company.objects.filter(caffe=request.user.caffe).all()
    for company in companies:
        elements.append({
            'edit_href': reverse('cash:edit_company', args=(company.id,)),
            'id': company.id,
            'desc': str(company)
        })

    return render(request, 'cash/new_element.html', {
        'form': form,
        'context': {
            'title': u'Nowa firma'
        },
        'elements': elements
    })


@permission_required('cash.change_company')
def cash_edit_company(request, company_id):
    """Show form to edit Company.

    Args:
        company_id (int): Id of Company which is edited.
    """

    company = get_object_or_404(
        Company,
        id=company_id,
        caffe=request.user.caffe
    )

    form = CompanyForm(
        request.POST or None,
        caffe=request.user.caffe,
        instance=company
    )

    if form.is_valid():
        form.save()
        messages.success(request, 'Firma została poprawnie zmieniona.')
        return redirect(reverse('cash:navigate'))

    return render(request, 'cash/edit_element.html', {
        'form': form,
        'context': {
            'title': u'Edytuj firmę',
            'cancel_href': reverse('cash:new_company')
        }
    })


@permission_required('cash.add_expense')
def cash_new_expense(request):
    """Show form to create new Expense and show already existing Expenses."""

    elements = []
    form = ExpenseForm(request.POST or None, caffe=request.user.caffe)

    if form.is_valid():
        form.save()
        messages.success(request, 'Wydatek został poprawnie dodany.')
        return redirect(reverse('cash:navigate'))

    expenses = Expense.objects.filter(caffe=request.user.caffe).all()
    for expense in expenses:
        elements.append({
            'edit_href': reverse('cash:edit_expense', args=(expense.id,)),
            'id': expense.id,
            'desc': str(expense)
        })

    return render(request, 'cash/new_element.html', {
        'form': form,
        'context': {
            'title': "Nowy wydatek"
        },
        'elements': elements
    })


@permission_required('cash.change_expense')
def cash_edit_expense(request, expense_id):
    """Show form to edit Expense.

    Args:
        expense_id (int): Id of Expense which is edited.
    """

    expense = get_object_or_404(
        Expense,
        id=expense_id,
        caffe=request.user.caffe
    )

    form = ExpenseForm(
        request.POST or None,
        caffe=request.user.caffe,
        instance=expense
    )

    if form.is_valid():
        form.save()
        messages.success(request, 'Wydatek został poprawnie zmieniony.')
        return redirect(reverse('cash:navigate'))

    return render(request, 'cash/edit_element.html', {
        'form': form,
        'context': {
            'title': 'Edytuj wydatek',
            'cancel_href': reverse('cash:new_expense')
        }
    })


@permission_required('cash.add_cashreport')
def cash_new_cash_report(request):
    """Show form to create CashReport and show already existing CashReport."""

    all_expenses = []
    form = CashReportForm(
        request.POST or None,
        caffe=request.user.caffe,
        creator=request.user
    )

    for expense in Expense.objects.filter(caffe=request.user.caffe).all():
        all_expenses.append({
            'id': expense.id,
            'name': expense.name,
            'selected': False,
            'amount': 0,
            'errors': {}
        })

        if expense.company:
            all_expenses[-1]['company'] = {
                'id': expense.company.id,
                'name': expense.company.name,
            }

    if request.POST:
        forms = []
        valid = form.is_valid()

        for full_expense in request.POST:
            fe_list = []

            try:
                full_expense = int(full_expense)
                fe_list = request.POST.getlist(str(full_expense))
            except ValueError:
                continue

            if len(fe_list) != 2:
                continue

            expense_form = FullExpenseForm(
                {'expense': fe_list[0], 'amount': fe_list[1]},
                caffe=request.user.caffe
            )

            valid = valid & expense_form.is_valid()

            expense = next(
                (e for e in all_expenses if e['id'] == int(fe_list[0])),
                None
            )

            if expense:
                expense['selected'] = True

                if expense_form.is_valid():
                    expense['amount'] = fe_list[1]
                    expense['errors'] = ''
                else:
                    expense['amount'] = ''
                    expense['errors'] = expense_form.errors.get('amount')

            forms.append(expense_form)

        if valid:
            cash_report = form.save()

            for form in forms:
                full_expense = form.save()
                full_expense.cash_report = cash_report
                full_expense.save()

            cash_report.save()
            messages.success(request, 'Raport z kasy został poprawnie dodany.')
            return redirect(reverse('cash:navigate'))
        else:
            messages.error(
                request, u'Formularz został niepoprawnie wypełniony.'
            )

    return render(request, 'cash/new.html', {
        'title':  'Nowy raport z kasy',
        'button': 'Dodaj',
        'form': form,
        'expenses': json.dumps(all_expenses),
    })


@permission_required('cash.change_cashreport')
def cash_edit_cash_report(request, report_id):
    """Show form to edit CashReport.

    Args:
        report_id (int): Id of CashReport which is edited.
    """

    cash_report = get_object_or_404(
        CashReport,
        id=report_id,
        caffe=request.user.caffe
    )

    form = CashReportForm(
        request.POST or None,
        caffe=request.user.caffe,
        creator=request.user,
        instance=cash_report
    )

    all_expenses = []
    for expense in Expense.objects.filter(caffe=request.user.caffe).all():
        all_expenses.append({
            'id': expense.id,
            'name': expense.name,
            'selected': False,
            'amount': 0,
            'errors': {}
        })

        if expense.company:
            all_expenses[-1]['company'] = {
                'id': expense.company.id,
                'name': expense.company.name,
            }

        full_expense = FullExpense.objects.filter(
            cash_report=cash_report.id, expense=expense.id
        ).first()

        if full_expense and (not request.POST):
            all_expenses[-1]['selected'] = True
            all_expenses[-1]['amount'] = full_expense.amount

    if request.POST:
        forms = []
        valid = form.is_valid()

        for full_expense in request.POST:
            fe_list = []

            try:
                full_expense = int(full_expense)
                fe_list = request.POST.getlist(str(full_expense))
            except ValueError:
                continue

            if len(fe_list) != 2:
                continue

            expense_form = FullExpenseForm(
                {'expense': fe_list[0], 'amount': fe_list[1]},
                caffe=request.user.caffe
            )

            valid = valid & expense_form.is_valid()

            expense = next(
                (e for e in all_expenses if e['id'] == int(fe_list[0])),
                None
            )

            if expense:
                expense['selected'] = True
                if expense_form.is_valid():
                    expense['amount'] = fe_list[1]
                    expense['errors'] = ''
                else:
                    expense['amount'] = ''
                    expense['errors'] = expense_form.errors.get('amount')

            forms.append(expense_form)

        if valid:
            cash_report = form.save()

            for full_expense in cash_report.full_expenses.all():
                full_expense.delete()

            for form in forms:
                full_expense = form.save()
                full_expense.cash_report = cash_report
                full_expense.save()

            cash_report.save()
            messages.success(
                request, 'Raport z kasy został poprawnie zmieniony.'
            )

            return redirect(reverse('cash:navigate'))
        else:
            messages.error(
                request, u'Formularz został niepoprawnie wypełniony.'
            )

    return render(request, 'cash/new.html', {
        'title':  'Nowy raport z kasy',
        'button': 'Uaktualnij',
        'form': form,
        'expenses': json.dumps(all_expenses),
    })


@permission_required('cash.view_cashreport')
def cash_show_cash_report(request, report_id):
    """Show CashReport with all Expenses.

    Args:
        report_id (int): Id of CashReport which have to be shown.
    """

    cash_report = get_object_or_404(
        CashReport,
        id=report_id,
        caffe=request.user.caffe
    )
    cash_report.balance = cash_report.balance()

    all_expenses = []
    for full_expense in cash_report.full_expenses.all():
        all_expenses.append({

caffe/templates/cash/edit_element.html
{% extends "home/base.html" %}
{% load tags %}

{% block title %}
  {{ context.title }}
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  {% for field in form %}
    <div class="input-line">
      {% with field|field_type as field_name %}
      {% if field_name == "Select" %}
        <div class="select-wrapper">
          {{ field }}
        </div>
      {% else %}
        {{ field }}
      {% endif %}
      {% endwith %}

      {{ field.label_tag }}
    </div>
    {{ field.errors }}

  {% endfor %}

  <button type="submit" class="button button-rounded button-green">Uaktualnij</button>
  <button type="cancel" class="button button-rounded button-red">
    <a href="{{ context.cancel_href }}">Anuluj</a>
  </button>
</form>
{% endblock %}

caffe/templates/cash/new.html
{% extends "home/base.html" %}
{% load tags %}

{% block title %}
  {{ title }}
{% endblock %}

{% block content %}

<script type="text/javascript">
(function ($, _) {
  "use strict"

  var expenses = [];

  var denominations = [
    {'value': 10, 'unit': 'gr', 'amount': 0.1},
    {'value': 20, 'unit': 'gr', 'amount': 0.2},
    {'value': 50, 'unit': 'gr', 'amount': 0.5},
    {'value': 1, 'unit': 'zł', 'amount': 1},
    {'value': 2, 'unit': 'zł', 'amount': 2},
    {'value': 5, 'unit': 'zł', 'amount': 5},
    {'value': 10, 'unit': 'zł', 'amount': 10},
    {'value': 20, 'unit': 'zł', 'amount': 20},
    {'value': 50, 'unit': 'zł', 'amount': 50},
    {'value': 100, 'unit': 'zł', 'amount': 100},
  ];

  function getExpense(id) {
    return _.find(expenses, function(expense) {
      return expense.id == id;
    });
  }

  function addExpenseToSelect(expense) {
    expense.chosen = false;

    $('#select-expenses').append('\
      <option id="' + expense.id + '" value="' + expense.id + '">' + expense.name + '</option>\
    ');
  }

  function removeExpenseFromSelect(expense) {
    var exp = $('#select-expenses').children('#' + expense.id);
    expense.chosen = true;

    if (exp.length) {
      exp.remove();
    }
  }

  function countBalance() {
    var expenses_inputs = $('.expenses input[type=number]');

    var expense_sum = 0.0;
    $.each(expenses_inputs, function(_, input) {
      if ($(input).val()) {
        expense_sum += parseFloat($(input).val());
      }
    });

    $('#expenses-sum').text(expense_sum);

    var inputs = [{
        'element': $('#id_cash_before_shift'),
        'sign': -1,
      }, {
        'element': $('#id_cash_after_shift'),
        'sign': 1,
      }, {
        'element': $('#id_card_payments'),
        'sign': 1,
      }, {
        'element': $('#id_amount_due'),
        'sign': -1,
      }
    ]

    var sum = 0.0;
    _.each(inputs, function(input) {
      if (input.element.val()) {
        sum += parseFloat(input.element.val()) * input.sign;
      }
    });

    var expenses = parseFloat($('#expenses-sum').text());
    if (expenses)
      sum += expenses;

    $('#balance').text(sum);

    var parent = $('#balance').parent()
      .removeClass('summary__value--red')
      .removeClass('summary__value--green');

    if (sum > 0.0) {
      parent.addClass('summary__value--green');
    } else if (sum < 0.0) {
      parent.addClass('summary__value--red');
    }
  }

  function events() {
    $('#select-expenses').on('change', function(event, obj) {
      var expense = getExpense(this.value);
      if (expense) {
        // remove expense from selected
        removeExpenseFromSelect(expense);

        var errorClasses = '', amount = '', errors = '';

        if (expense.selected) {
          amount = expense.amount;

          if (!_.isEmpty(expense.errors)) {
            // add error if error occured
            errors = '<ul class="errorlist">';
              _.each(expense.errors, function(error) {
                errors += '<li>' + error + '</li>';
              });
            errors += '</ul>';

            // change input border color if error occured
            errorClasses = 'error';
          }

          expense.selected = false;
        }

        $('.expenses')
          .append(
            '<div id="' + expense.id + '" class="expense">' +
              '<input type="hidden" name="' + expense.id + '" value="' + expense.id + '"/>\
              <div class="name">\
                ' + expense.name +'\
              </div>\
              <div class="amount">\
                <input type="number" name="' + expense.id + '" value="' + amount + '" class="' + errorClasses + '"/>\
              </div>\
              <div class="unit">zł</div>\
              <div class="trash">\
                <i class="fa fa-trash-o" aria-hidden="true"></i>' +
              '</div>' +
            '</div>'
          )
          .append(errors);
      }
    });

    $(document).on('click', '.trash', function() {
      var expense = $(this).closest('.expense');

      var exp = getExpense(expense.attr('id'));
      if (exp) {
        addExpenseToSelect(exp);

        var errors = $(expense).next('ul');
        if (errors)
          errors.remove(); // remove error

        expense.remove();
      }

      countBalance();
    });

    $(document).on('input', '.denomination', function() {
      var sum = 0.0;
      _.each(denominations, function(denomination, index) {
        if ($('#denomination-' + index).val()) {
          sum += parseInt($('#denomination-' + index).val()) * denomination.amount;
        }
      });

      $('#id_cash_after_shift').val(sum);
      countBalance();
    });

    $(document).on('input', '.expenses input[type=number]', function() {
      countBalance();
    });

    $(document).on('input', '.money input', function() {
      countBalance();
    });

    $(document).on('click', '#toggle-denominations', function() {
      $(this).html($(this).html() == '<i class="fa fa-caret-right"></i>' ? '<i class="fa fa-caret-left"></i>' : '<i class="fa fa-caret-right"></i>');
      $(this).closest('.column').next().toggle();
    });
  }

  $(document).ready(function() {
    expenses = {{ expenses|safe }};

    events();

    _.each(expenses, function(expense) {
      addExpenseToSelect(expense);

      if (expense.selected) {
        $('#select-expenses').find('#' + expense.id).parent().val(expense.id).trigger(
          'change'
        );

        removeExpenseFromSelect(expense);
      }
    });

    _.each(denominations, function(denomination, index) {
      $('.denominations').append(
        '<div class="input-line">' +
          '<span>' + denomination.value + ' ' + denomination.unit + ':</span> <input id="denomination-' + index + '" type="number" class="denomination" value="0"/>' +
        '</div>'
      );
    });

    countBalance();
  });
})(jQuery, _);
</script>

<form method="POST" class="cash-form">
  {% csrf_token %}

  <div class="column">
    <div class="input-line">
      <div class="select-wrapper">
        <select id="select-expenses">
          <option name="expense" id="-1" value="-1">-------------</option>
        </select>
      </div>
      <label for="">Wybierz wydatek</label>
    </div>

    <div class="expenses"></div>
  </div>

  <div class="column">
    <div class="money">
      <div class="input-line">
        {{ form.cash_before_shift }}
        {{ form.cash_before_shift.label_tag }}
      </div>
      {{ form.cash_before_shift.errors }}

      <div class="input-line smaller">
        {{ form.cash_after_shift }}
        {{ form.cash_after_shift.label_tag }}

        <div id="toggle-denominations" class="toggle"><i class="fa fa-caret-right"></i></div>
      </div>
      {{ form.cash_after_shift.errors }}

      <div class="input-line">
        {{ form.card_payments }}
        {{ form.card_payments.label_tag }}
      </div>
      {{ form.card_payments.errors }}

      <div class="input-line">
        {{ form.amount_due }}
        {{ form.amount_due.label_tag }}
      </div>
      {{ form.amount_due.errors }}
    </div>

    <ul class="summary summary--right">
      <li>
        <div class="summary__description">
          Suma wydatków:
        </div>
        <div class="summary__value">
          <span id="expenses-sum">0</span> zł
        </div>
      </li>
      <li>
        <div class="summary__description">
          Saldo:
        </div>
        <div class="summary__value">
          <span id="balance">0</span> zł
        </div>
      </li>
    </ul>
  </div>

  <div class="column" style="display: none;">
    <div class="denominations"></div>
  </div>

  <div class="column">
    <button type="submit" class="button button-rounded button-green">{{ button }}</button>
  </div>
</form>
{% endblock %}

caffe/templates/cash/new_element.html
{% extends "home/base.html" %}
{% load tags %}

{% block title %}
  {{ context.title }}
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  {% for field in form %}
    <div class="input-line">
      {% with field|field_type as field_name %}
      {% if field_name == "Select" %}
        <div class="select-wrapper">
          {{ field }}
        </div>
      {% else %}
        {{ field }}
      {% endif %}
      {% endwith %}

      {{ field.label_tag }}
    </div>
    {{ field.errors }}

  {% endfor %}

  <button type="submit" class="button button-rounded button-green">Dodaj</button>
</form>

<h2 class="elements-subtitle">
  Już istniejące
</h2>

<ul class="elements">
  {% for element in elements %}
    <li class="element">
      <span class="desc">
        {{ element.desc }}
      </span>
      <a href="{{ element.edit_href }}" class="button button-rounded button-small button-red">
        Edytuj
      </a>
    </li>
  {% endfor %}
</ul>
{% endblock %}

caffe/templates/cash/show.html
{% extends "home/base.html" %}

{% block title %}
Raport z kasy
{% endblock %}

{% block content %}
<section class="cash-report__title">
  {{ report.created_on }}
</section>

{% if perms.cash.edit_cashreport %}
  <section class="buttons">
    <a href="{% url 'edit_cash_report' report.id %}" class="button button-rounded button-red">
      Edytuj
    </a>
  </section>
{% endif %}

<section class="row">
  <div class="column">
    <div class="subtitle">
      Zestawienie
    </div>

    <table>
      <thead>
        <tr>
          <th width="65%">Nazwa</th>
          <th>Ilość</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>Pieniądze przed zmianą</td>
          <td class="table__cell--font-fixed">-{{ report.cash_before_shift }} zł</td>
        </tr>
        <tr>
          <td>Pieniądze po zmianie</td>
          <td class="table__cell--font-fixed">{{ report.cash_after_shift }} zł</td>
        </tr>
        <tr>
          <td>Karty</td>
          <td class="table__cell--font-fixed">{{ report.card_payments }} zł</td>
        </tr>
        <tr>
          <td>Łączna należność</td>
          <td class="table__cell--font-fixed">-{{ report.amount_due }} zł</td>
        </tr>
        <tr>
          <td class="table__cell--highlight">Saldo</td>
          {% if report.balance > 0 %}
            <td class="table__cell--font-fixed table__cell--highlight table__cell--font-green">{{ report.balance }} zł</td>
          {% elif report.balance < 0 %}
            <td class="table__cell--font-fixed table__cell--highlight table__cell--font-red">{{ report.balance }} zł</td>
          {% else %}
            <td class="table__cell--font-fixed table__cell--highlight">{{ report.balance }} zł</td>
          {% endif %}
        </tr>
      </tbody>
    </table>
  </div>

  <div class="column">
    <div class="subtitle">
      Wydatki
    </div>

    <table>
      <thead>
        <tr>
          <th width="65%">Nazwa</th>
          <th>Ilość</th>
        </tr>
      </thead>

      <tbody>
        {% for expense in expenses %}
          <tr>
            <td>{{ expense.name }}</td>
            <td class="table__cell--font-fixed">{{ expense.amount }} zł</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endblock %}