caffe/caffe/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import index_navigate, caffe_create

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', index_navigate, name='index_navigate'),
    url(r'^create/$', caffe_create, name='caffe_create'),

    url(r'cafe/', include('home.urls', namespace='home')),
    url(r'reports/', include('reports.urls', namespace='reports')),
    url(r'stencils/', include('stencils.urls', namespace='stencils')),
    url(r'employees/', include('employees.urls', namespace='employees')),
    url(r'statistics/', include('stats.urls', namespace='statistics')),
    url(r'calendar/', include('calendars.urls', namespace='calendar')),
    url(r'hours/', include('hours.urls', namespace='hours')),
    url(r'cash/', include('cash.urls', namespace='cash')),
]

caffe/cash/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (cash_edit_cash_report, cash_edit_company,
                    cash_edit_expense, cash_navigate, cash_new_cash_report,
                    cash_new_company, cash_new_expense,
                    cash_show_cash_report)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', cash_navigate, name='navigate'),
    url(r'^(?P<report_id>\d{0,17})/$', cash_show_cash_report, name='show'),
    url(r'^new/$', cash_new_cash_report, name='new'),
    url(
        r'^edit/(?P<report_id>\d{0,17})/$',
        cash_edit_cash_report,
        name='edit'
    ),

    url(r'^new/company/$', cash_new_company, name='new_company'),
    url(
        r'^edit/company/(?P<company_id>\d{0,17})/$',
        cash_edit_company,
        name='edit_company'
    ),

    url(r'^new/expense/$', cash_new_expense, name='new_expense'),
    url(r'^edit/expense/(?P<expense_id>\d{0,17})/$',
        cash_edit_expense, name='edit_expense'),
]

caffe/home/urls.py
from django.conf.urls import url
from django.contrib import admin

from home.views import caffe_navigate

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', caffe_navigate, name='navigate'),
]

caffe/hours/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (hours_edit_position, hours_edit_worked_hours,
                    hours_new_position, hours_new_worked_hours)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^new/$', hours_new_worked_hours, name='new'),
    url(
        r'^edit/(?P<hours_pk>\d{0,17})/$',
        hours_edit_worked_hours,
        name='edit'
    ),

    url(r'^position/new/$', hours_new_position, name='new_position'),
    url(
        r'^position/edit/(?P<position_pk>\d{0,17})/$',
        hours_edit_position,
        name='edit_position'
    ),
]

caffe/reports/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (reports_edit_category, reports_edit_product,
                    reports_edit_report, reports_edit_unit, reports_navigate,
                    reports_new_category, reports_new_product,
                    reports_new_report, reports_new_unit,
                    reports_show_report)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', reports_navigate, name='navigate'),
    url(r'^(?P<report_id>\d{0,17})/$', reports_show_report, name='show'),
    url(r'^new/$', reports_new_report, name='new'),
    url(r'^edit/(?P<report_id>\d{0,17})/$', reports_edit_report, name='edit'),

    url(r'^new/category/$', reports_new_category, name='new_category'),
    url(
        r'^edit/category/(?P<category_id>\d{0,17})/$',
        reports_edit_category,
        name='edit_category'
    ),

    url(r'^new/unit/$', reports_new_unit, name='new_unit'),
    url(
        r'^edit/unit/(?P<unit_id>\d{0,17})/$',
        reports_edit_unit,
        name='edit_unit'
    ),

    url(r'^new/product/$', reports_new_product, name='new_product'),
    url(
        r'^edit/product/(?P<product_id>\d{0,17})/$',
        reports_edit_product,
        name='edit_product'
    ),
]

caffe/stencils/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (stencils_edit_stencil, stencils_new_report,
                    stencils_new_stencil, stencils_show_all_stencils,
                    stencils_show_stencil)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^all/$', stencils_show_all_stencils, name='all'),
    url(
        r'^show/(?P<stencil_id>\d{0,17})/$',
        stencils_show_stencil,
        name='show'
    ),
    url(r'^new/$', stencils_new_stencil, name='new'),
    url(
        r'^edit/(?P<stencil_id>\d{0,17})/$',
        stencils_edit_stencil,
        name='edit'
    ),

    url(r'^new/report/(?P<stencil_id>\d{0,17})/$',
        stencils_new_report, name='new_report'),
]

caffe/cash/models.py
"""Module with all models related to cash reports."""

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.utils.translation import ugettext_lazy as _


class Company(models.Model):
    """Stores one company a cafe interacts with (e.g., GoodCake bakery)."""

    name = models.CharField(max_length=200)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        self.full_clean()
        super(Company, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class Expense(models.Model):
    """Represents an object a cafe pays for during the day (e.g., cakes).

    One entry could look like this:
    (name: cakes, company: GoodCake) or
    (name: newspapers).
    """

    name = models.CharField(max_length=300)
    company = models.ForeignKey('Company', blank=True, null=True)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name', 'company')
        default_permissions = ('add', 'change', 'delete', 'view')

    def clean(self, *args, **kwargs):
        """Clean data and check validation."""

        # checks if there exists two products with same name
        query = Expense.objects.filter(name=self.name, caffe=self.caffe)
        if self.pk:
            query = query.exclude(pk=self.pk)

        if query.exists():
            raise ValidationError(
                _('Wydatek powinien mieć unikalną nazwę.')
            )

        super(Expense, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.company:
            if self.caffe != self.company.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia firmy nie zgadza się.')
                )

        self.full_clean()
        super(Expense, self).save(*args, **kwargs)

    def __str__(self):
        return '{}, {}'.format(self.name, self.company)


class FullExpense(models.Model):
    """Stores one specific expense - expense and amount.

    Is assigned to one report and can't be reused.
    """

    expense = models.ForeignKey('Expense')
    amount = models.FloatField()
    cash_report = models.ForeignKey(
        'CashReport',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='full_expenses'
    )
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        default_permissions = ('add', 'change', 'delete', 'view')

    def clean(self, *args, **kwargs):
        """Clean data and check validation."""

        # checks if there exists two same expenses
        full_expenses = []
        if self.cash_report is not None:
            full_expenses = self.cash_report.full_expenses.all()

        for full_expense in full_expenses:
            if full_expense.expense == self.expense:
                raise ValidationError(
                    _('Cash Report should not contain two same expenses.')
                )

        super(FullExpense, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.cash_report:
            if self.caffe != self.cash_report.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia raportu z kasy nie zgadza się.')
                )

        if self.caffe != self.expense.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia wydatku nie zgadza się.')
            )

        self.full_clean()
        super(FullExpense, self).save(*args, **kwargs)

    def __str__(self):
        return '{}: {}'.format(self.expense, self.amount)


class CashReport(models.Model):
    """Stores a single report representing money flow during one shift."""

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey('employees.Employee')
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    cash_before_shift = models.FloatField()
    cash_after_shift = models.FloatField()
    card_payments = models.FloatField()
    amount_due = models.FloatField()

    class Meta:
        ordering = ('-created_on', '-updated_on')
        default_permissions = ('add', 'change', 'delete', 'view')

    def balance(self):
        """Calculate balance within one report, indicate deficit/surplus."""

        expenses = 0
        if self.full_expenses.count() > 0:
            expenses = (
                self.full_expenses.aggregate(Sum('amount'))['amount__sum']
            )

        return (self.cash_after_shift + self.card_payments + expenses - \
                self.cash_before_shift - self.amount_due)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.creator is not None:
            if self.caffe != self.creator.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia tworzącego powinna się zgadzać')
                )

        self.full_clean()
        super(CashReport, self).save(*args, **kwargs)

    def __str__(self):
        return 'Report created: {:%Y-%m-%d %H:%M} by {}'.format(
            self.created_on,
            self.creator
        )

caffe/employees/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Employee(AbstractUser):
    """Employee model, extends AbstractUser fields."""

    telephone_number = models.CharField(max_length=20, blank=True)
    favorite_coffee = models.CharField(max_length=50, blank=True)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('last_name', 'first_name',)
        default_permissions = ('add', 'change', 'delete', 'view')

caffe/reports/models.py
"""Defines all the classes needed to create a Report from scratch.

Report: a single document about the state of a cafe.
Category: a class of products sharing common characteristics.
Product: a single item in a cafe.
Unit: a measure of products.
FullProduct: a product with its quantity.
"""

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Report(models.Model):
    """Stores a single report created from selected FullProducts.

    Date of creation is set automatically.
    Currently logged in user is assigned to report as creator.
    """

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        'employees.Employee',
        null=True,
        blank=True,
        default=None
    )
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('-created_on',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.creator is not None:
            if self.caffe != self.creator.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia tworzącego powinna się zgadzać')
                )

        self.full_clean()
        super(Report, self).save(*args, **kwargs)

    def __str__(self):
        return 'Report created: {:%Y-%m-%d %H:%M} {}'.format(
            self.created_on,
            self.creator
        )


class Category(models.Model):
    """Stores the category of a product, e.g. cake, tea, sandwich.

    Intended to be created once and then to reuse it in future reports.
    """

    name = models.CharField(max_length=100)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        self.full_clean()
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class Unit(models.Model):
    """Stores a type of unit used to count the amount of products.

    Intended to be created once and then to reuse it in future reports.
    """

    name = models.CharField(max_length=100)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        self.full_clean()
        super(Unit, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    """Stores a specific product, e.g. brownie, earl grey, PB&J sandwich.

    Intended to be created once and then to reuse it in future reports.
    Unit specifies how the amount of product is counted.
    """

    name = models.CharField(max_length=100)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    unit = models.ForeignKey('Unit', on_delete=models.CASCADE)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.caffe != self.category.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia kategorii nie zgadza się.')
            )

        if self.caffe != self.unit.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia jednostki nie zgadza się.')
            )

        self.full_clean()
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class FullProduct(models.Model):
    """Stores a product with its quantity.

    Intended to be used once, only in one report.
    """

    product = models.ForeignKey('Product')
    amount = models.FloatField(validators=[MinValueValidator(0)])
    report = models.ForeignKey(
        'Report',
        blank=True,
        null=True,
        related_name='full_products'
    )
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    def clean(self, *args, **kwargs):
        """Clean data and check validation."""

        # checks if there exists two same products
        full_products = []
        if self.report is not None:
            full_products = self.report.full_products.all()

        for full_product in full_products:
            if full_product.product == self.product:
                raise ValidationError(
                    _('Report should not contain two same products.')
                )

        super(FullProduct, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.report:
            if self.caffe != self.report.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia raportu nie zgadza się.')
                )

        if self.caffe != self.product.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia produktu nie zgadza się.')
            )

        self.full_clean()
        super(FullProduct, self).save(*args, **kwargs)

    def __str__(self):
        return '{0}, {1:g} {2}'.format(
            self.product,
            self.amount,
            self.product.unit
        )

caffe/templates/home/base.html
{% extends "home/head.html" %}

{% load staticfiles %}
{% load tags %}

{% block page %}
  <div class="container">
    <div class="left-pane open">
      <ul class="navigation">
        <li>
          <a href="{% url 'home:navigate' %}" class="{% active 'cafe' %}">
            <i class="fa fa-coffee"></i>
            <div class="description">Kawiarnia</div>
          </a>
        </li>
        <li>
          <a href="{% url 'reports:navigate' %}" class="{% active 'reports' %} {% active 'stencils' %}">
            <i class="fa fa-files-o"></i>
            <div class="description">Raporty</div>
          </a>
        </li>
        <li>
          <a href="{% url 'cash:navigate' %}" class="{% active 'cash' %}">
            <i class="fa fa-money"></i>
            <div class="description">Kasa</div>
          </a>
        </li>
        <li>
          <a href="{% url 'employees:navigate' %}" class="{% active 'employees' %}">
            <i class="fa fa-user"></i>
            <div class="description">Konta</div>
          </a>
        </li>
        <li>
          <a href="{% url 'calendar:navigate' %}" class="{% active 'calendar' %}">
            <i class="fa fa-calendar-o"></i>
            <div class="description">Kaledarz</div>
          </a>
        </li>
        <li>
          <a href="{% url 'statistics:navigate' %}" class="{% active 'statistics' %}">
            <i class="fa fa-line-chart"></i>
            <div class="description">Statystki</div>
          </a>
        </li>
      </ul>

      <div id="control-menu" class="expand"></div>
    </div>
    <div class="right-pane">
      <div class="navigation">
        <div class="navigation__settings">
          {% if not user.is_authenticated %}
            <a href="{% url 'employees:login' %}" class="button button-orange">
              Zaloguj
            </a>
          {% else %}
            <span class="navigation__settings__welcome">Witaj, {{ user.first_name }} {{ user.last_name }}</span>
            <a href="{% url 'employees:logout' %}" class="button button-light-blue">
              Wyloguj
            </a>
          {% endif %}
        </div>
      </div>

      <div class="right-pane-container">
        <button class="button button-light-blue back-button">
          <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
        </button>

        <h1 class="header">
          {% block title %}
          {% endblock %}
        </h1>

        {% if messages %}
          <div class="alerts">
            {% for message in messages %}
              <div class="alert alert-rounded {{ message.tags }}">{{ message }}</div>
            {% endfor %}
          </div>
        {% endif %}

        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

caffe/templates/home/caffe.html
{% extends "home/base.html" %}

{% block title %}
Kawiarnia
{% endblock %}

{% block content %}

<section class="cards cards-green">
  <h2 class="card-subtitle">
    Stwórz
  </h2>

  {% if perms.reports.add_report %}
    <a href="{% url 'reports_new_report' %}" class="card">
      <i class="fa fa-wpforms" aria-hidden="true"></i>
      Raport
    </a>
  {% endif %}

  {% if perms.cash.add_cashreport %}
    <a href="{% url 'new_cash_report' %}" class="card">
      <i class="fa fa-money" aria-hidden="true"></i>
        Raporty z kasy
    </a>
  {% endif %}

  {% if perms.hours.add_workedhours %}
    <a href="{% url 'new_worked_hours' %}" class="modaal card">
      <i class="fa fa-clock-o" aria-hidden="true"></i>
      Przepracowane godziny
    </a>
  {% endif %}
</section>

<div class="subtitle">
  Raporty
</div>
<section class="reports">
  {% for report in reports %}
    <div class="report">
      <div class="meta">
        {{ report.created_on }}
      </div>

      <a href="{% url 'reports_show_report' report.id %}" class="button button-rounded button-blue button-with-icon">
        <i class="fa fa-search" aria-hidden="true"></i>
        <span>
          Pokaż raport
        </span>
      </a>
    </div>
  {% endfor %}
</section>

<div class="subtitle">
  Raporty z kasy
</div>
<section class="cash-reports">
  {% for report in cash_reports %}
    <div class="cash-report">
      <div class="cash-report__smeta">
        {{ report.created_on }}
      </div>

      <a href="{% url 'show_cash_report' report.id %}" class="button button-rounded button-blue button-with-icon">
        <i class="fa fa-search" aria-hidden="true"></i>
        <span>
          Pokaż raport z kasy
        </span>
      </a>
    </div>
  {% endfor %}
</section>


<div class="subtitle">
  Przepracowane godziny
</div>
<section id="worked-hours">
  <table>
    <thead>
      <tr>
        <th>Kto</th>
        <th>Od której</th>
        <th>Do której</th>
        <th>Stanowisko</th>
        {% if perms.hours.edit_workedhours %}
          <th class="center">Edytuj</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for hour in worked_hours %}
        <tr>
          <td>{{ hour.employee.first_name }}</td>
          <td>{{ hour.start_time }}</td>
          <td>{{ hour.end_time }}</td>
          <td>{{ hour.position.name }}</td>
          {% if perms.hours.edit_workedhours %}
            <td class="table__cell--center icon edit"><a href="{% url 'edit_worked_hours' hour.id %}"><i class="fa fa-pencil"></i></a></td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
{% endblock %}

caffe/templates/home/calendar.html
{% extends "home/base.html" %}

{% block title %}
Kalendarz
{% endblock %}

{% block content %}
<script type="text/javascript">
(function($) {
  $(document).ready(function() {
    $('#calendar').calendar();
  });
}(jQuery));
</script>

<section id="calendar"></section>
{% endblock %}

caffe/templates/home/cash.html
{% extends "home/base.html" %}

{% block title %}
Kasa
{% endblock %}

{% block content %}
<section class="cards cards-primary">
  {% if perms.cash.add_cashreport %}
    <a href="{% url 'cash:new' %}" class="card">
      <i class="fa fa-money" aria-hidden="true"></i>
      Nowy raport z kasy
    </a>
  {% endif %}
</section>

<section class="cards cards-green">
  <h2 class="card-subtitle">
    Tworzenie elementów raportu z kasy
  </h2>

  {% if perms.cash.add_company %}
    <a href="{% url 'cash:new_company' %}" class="card">
      <i class="fa fa-building-o" aria-hidden="true"></i>
      Firma
    </a>
  {% endif %}

  {% if perms.cash.add_expense %}
    <a href="{% url 'cash:new_expense' %}" class="card">
      <i class="fa fa-dollar" aria-hidden="true"></i>
      Wydatki
    </a>
  {% endif %}
</section>

<section class="cards cards-red">
  <h2 class="card-subtitle">
    Podgląd i edycja
  </h2>

  {% if perms.cash.view_company %}
    <a href="{% url 'cash:new_company' %}" class="card">
      <i class="fa fa-building-o" aria-hidden="true"></i>
      Firmy
    </a>
  {% endif %}

  {% if perms.cash.view_expense %}
    <a href="{% url 'cash:new_expense' %}" class="card">
      <i class="fa fa-dollar" aria-hidden="true"></i>
      Wydatki
    </a>
  {% endif %}
</section>
{% endblock %}

caffe/templates/home/employees.html
{% extends "home/base.html" %}

{% block title %}
Pracownicy
{% endblock %}

{% block content %}
<section class="cards cards-primary">
  {% if perms.employees.add_employee %}
    <a href="{% url 'employees:new' %}" class="card">
      <i class="fa fa-user-plus" aria-hidden="true"></i>
      Nowy pracownik
    </a>
  {% endif %}

  {% if perms.hours.add_position %}
    <a href="{% url 'hours:new_position' %}" class="card">
      <i class="fa fa-user" aria-hidden="true"></i>
      Stanowisko
    </a>
  {% endif %}

  <a href="{% url 'employees:login' %}" class="card">
    <i class="fa fa-sign-in" aria-hidden="true"></i>
    Zaloguj
  </a>
</section>

<section class="cards cards-red">
  <h2 class="card-subtitle">
    Podgląd i edycja
  </h2>

  <a href="{% url 'employees:all' %}" class="card">
    <i class="fa fa-users" aria-hidden="true"></i>
    Pracownicy
  </a>

  {% if perms.hours.add_position %}
    <a href="{% url 'hours:new_position' %}" class="card">
      <i class="fa fa-user" aria-hidden="true"></i>
      Stanowiska
    </a>
  {% endif %}
</section>
{% endblock %}

caffe/templates/home/head.html
{% load staticfiles %}
{% load tags %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
  <head>
  {% block head %}
    <title>Caffe</title>

    <link charset="utf-8" rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link charset="utf-8" rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <script type="text/javascript" src="{% static 'js/jquery.2.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/js.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/lodash.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/calendar.js' %}"></script>
  {% endblock %}
  </head>
  <body>
    {% block page %}

    {% endblock %}
    <script type="text/javascript" src="{% static 'js/functions.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/modaal.js' %}"></script>
  </body>
</html>

caffe/templates/home/reports.html
{% extends "home/base.html" %}

{% block title %}
Raporty i szablony
{% endblock %}

{% block content %}
<section class="cards cards-primary">
  {% if perms.reports.add_report %}
    <a href="{% url 'reports:new' %}" class="card">
      <i class="fa fa-wpforms" aria-hidden="true"></i>
      Nowy raport
    </a>
  {% endif %}

  <a href="{% url 'stencils:all' %}" class="card">
    <i class="fa fa-copy" aria-hidden="true"></i>
    Nowy raport z szablonu
  </a>
</section>

<section class="cards cards-green">
  <h2 class="card-subtitle">
    Tworzenie elementów raportu
  </h2>

  <a href="{% url 'reports:new_unit' %}" class="card">
    <i class="fa fa-percent" aria-hidden="true"></i>
    Jednostki
  </a>
  <a href="{% url 'reports:new_category' %}" class="card">
    <i class="fa fa-columns" aria-hidden="true"></i>
    Kategorie
  </a>
  <a href="{% url 'reports:new_product' %}" class="card">
    <i class="fa fa-tag" aria-hidden="true"></i>
    Produkty
  </a>

  {% if perms.stencils.add_stencil %}
    <a href="{% url 'stencils:new' %}" class="card">
      <i class="fa fa-edit" aria-hidden="true"></i>
      Szablony
    </a>
  {% endif %}
</section>

<section class="cards cards-red">
  <h2 class="card-subtitle">
    Podgląd i edycja
  </h2>

  <a href="{% url 'reports:new_unit' %}" class="card">
    <i class="fa fa-percent" aria-hidden="true"></i>
    Jednostki
  </a>
  <a href="{% url 'reports:new_category' %}" class="card">
    <i class="fa fa-columns" aria-hidden="true"></i>
    Kategorie
  </a>
  <a href="{% url 'reports:new_product' %}" class="card">
    <i class="fa fa-tag" aria-hidden="true"></i>
    Produkty
  </a>
  <a href="{% url 'stencils:all' %}" class="card">
    <i class="fa fa-edit" aria-hidden="true"></i>
    Szablony
  </a>
</section>
{% endblock %}

caffe/templates/home/statistics.html
{% extends "home/base.html" %}

{% block title %}
Statystki
{% endblock %}

{% block content %}
<section class="statistics">
  <div class="statistic">
    <div class="info">
      10
    </div>

    <div class="description">
      Pracowników
    </div>
  </div>

  <div class="statistic">
    <div class="info">200</div>

    <div class="description">
      Raportów
    </div>
  </div>

  <div class="statistic">
    <div class="info">1'000 $</div>

    <div class="description">
      W kasie
    </div>
  </div>
</section>
{% endblock %}