caffe/caffe/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import index_navigate, caffe_create

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', index_navigate, name='index_navigate'),
    url(r'^create/$', caffe_create, name='caffe_create'),

    url(r'cafe/', include('home.urls', namespace='home')),
    url(r'reports/', include('reports.urls', namespace='reports')),
    url(r'stencils/', include('stencils.urls', namespace='stencils')),
    url(r'employees/', include('employees.urls', namespace='employees')),
    url(r'statistics/', include('stats.urls', namespace='statistics')),
    url(r'calendar/', include('calendars.urls', namespace='calendar')),
    url(r'hours/', include('hours.urls', namespace='hours')),
    url(r'cash/', include('cash.urls', namespace='cash')),
]

caffe/cash/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (cash_edit_cash_report, cash_edit_company,
                    cash_edit_expense, cash_navigate, cash_new_cash_report,
                    cash_new_company, cash_new_expense,
                    cash_show_cash_report)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', cash_navigate, name='navigate'),
    url(r'^(?P<report_id>\d{0,17})/$', cash_show_cash_report, name='show'),
    url(r'^new/$', cash_new_cash_report, name='new'),
    url(
        r'^edit/(?P<report_id>\d{0,17})/$',
        cash_edit_cash_report,
        name='edit'
    ),

    url(r'^new/company/$', cash_new_company, name='new_company'),
    url(
        r'^edit/company/(?P<company_id>\d{0,17})/$',
        cash_edit_company,
        name='edit_company'
    ),

    url(r'^new/expense/$', cash_new_expense, name='new_expense'),
    url(r'^edit/expense/(?P<expense_id>\d{0,17})/$',
        cash_edit_expense, name='edit_expense'),
]

caffe/stencils/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (stencils_edit_stencil, stencils_new_report,
                    stencils_new_stencil, stencils_show_all_stencils,
                    stencils_show_stencil)

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^all/$', stencils_show_all_stencils, name='all'),
    url(
        r'^show/(?P<stencil_id>\d{0,17})/$',
        stencils_show_stencil,
        name='show'
    ),
    url(r'^new/$', stencils_new_stencil, name='new'),
    url(
        r'^edit/(?P<stencil_id>\d{0,17})/$',
        stencils_edit_stencil,
        name='edit'
    ),

    url(r'^new/report/(?P<stencil_id>\d{0,17})/$',
        stencils_new_report, name='new_report'),
]

caffe/reports/models.py
"""Defines all the classes needed to create a Report from scratch.

Report: a single document about the state of a cafe.
Category: a class of products sharing common characteristics.
Product: a single item in a cafe.
Unit: a measure of products.
FullProduct: a product with its quantity.
"""

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Report(models.Model):
    """Stores a single report created from selected FullProducts.

    Date of creation is set automatically.
    Currently logged in user is assigned to report as creator.
    """

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        'employees.Employee',
        null=True,
        blank=True,
        default=None
    )
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('-created_on',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.creator is not None:
            if self.caffe != self.creator.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia tworzącego powinna się zgadzać')
                )

        self.full_clean()
        super(Report, self).save(*args, **kwargs)

    def __str__(self):
        return 'Report created: {:%Y-%m-%d %H:%M} {}'.format(
            self.created_on,
            self.creator
        )


class Category(models.Model):
    """Stores the category of a product, e.g. cake, tea, sandwich.

    Intended to be created once and then to reuse it in future reports.
    """

    name = models.CharField(max_length=100)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        self.full_clean()
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class Unit(models.Model):
    """Stores a type of unit used to count the amount of products.

    Intended to be created once and then to reuse it in future reports.
    """

    name = models.CharField(max_length=100)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        self.full_clean()
        super(Unit, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    """Stores a specific product, e.g. brownie, earl grey, PB&J sandwich.

    Intended to be created once and then to reuse it in future reports.
    Unit specifies how the amount of product is counted.
    """

    name = models.CharField(max_length=100)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    unit = models.ForeignKey('Unit', on_delete=models.CASCADE)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name',)
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.caffe != self.category.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia kategorii nie zgadza się.')
            )

        if self.caffe != self.unit.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia jednostki nie zgadza się.')
            )

        self.full_clean()
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.name)


class FullProduct(models.Model):
    """Stores a product with its quantity.

    Intended to be used once, only in one report.
    """

    product = models.ForeignKey('Product')
    amount = models.FloatField(validators=[MinValueValidator(0)])
    report = models.ForeignKey(
        'Report',
        blank=True,
        null=True,
        related_name='full_products'
    )
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    def clean(self, *args, **kwargs):
        """Clean data and check validation."""

        # checks if there exists two same products
        full_products = []
        if self.report is not None:
            full_products = self.report.full_products.all()

        for full_product in full_products:
            if full_product.product == self.product:
                raise ValidationError(
                    _('Report should not contain two same products.')
                )

        super(FullProduct, self).clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        """Save model into the database."""

        if self.report:
            if self.caffe != self.report.caffe:
                raise ValidationError(
                    _('Kawiarnia i kawiarnia raportu nie zgadza się.')
                )

        if self.caffe != self.product.caffe:
            raise ValidationError(
                _('Kawiarnia i kawiarnia produktu nie zgadza się.')
            )

        self.full_clean()
        super(FullProduct, self).save(*args, **kwargs)

    def __str__(self):
        return '{0}, {1:g} {2}'.format(
            self.product,
            self.amount,
            self.product.unit
        )

caffe/stencils/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _

from reports.models import Category


class Stencil(models.Model):
    """Stores template of Report which can be used to create Reports faster.

    Attributes:
        name (str): Name for given Stencil.
        description (Optional(str)): Description for Stencil which should
            describe why this Stencil exists or add additional informations.
        categories (List(Category)): Categories which are used in creating
            Report from this Stencil.
    """

    name = models.CharField(max_length=100,)
    description = models.TextField(max_length=500, null=True, blank=True,)
    categories = models.ManyToManyField(Category)
    caffe = models.ForeignKey(
        'caffe.Caffe',
        null=True,
        blank=False,
        default=None
    )

    class Meta:
        ordering = ('name', 'description')
        unique_together = ('name', 'caffe',)
        default_permissions = ('add', 'change', 'delete', 'view')

    def save(self, *args, **kwargs):
        """Save model into the database."""

        self.full_clean()
        super(Stencil, self).save(*args, **kwargs)

        if self.categories is not None:
            for category in self.categories.all():
                if self.caffe != category.caffe:
                    raise ValidationError(
                        _('Kawiarnia i kawiarnia kategorii nie zgadza się.')
                    )

    def __str__(self):
        return '{}'.format(self.name)

caffe/stencils/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from reports.models import Category

from .models import Stencil


class StencilForm(forms.ModelForm):
    """Responsible for proper saving Stencil model."""

    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.none(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Stencil
        fields = ('name', 'description', 'categories',)

    def __init__(self, *args, **kwargs):
        """Initialize all necessary information of form."""

        self._caffe = kwargs.pop('caffe')

        kwargs.setdefault('label_suffix', '')  # removes ":" from labels
        super(StencilForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Nazwa'
        self.fields['description'].label = 'Opis'
        self.fields['categories'].label = 'Kategorie'

        self.fields['categories'].queryset = (
            Category.objects.filter(caffe=self._caffe).all()
        )

        if self.instance.id:
            # set initially selected categories
            categories = self.instance.categories
            self.initial['categories'] = [
                category.id for category in categories.order_by('name')
            ]

    def clean_name(self):
        """Check name field."""

        name = self.cleaned_data['name']
        query = Stencil.objects.filter(name=name, caffe=self._caffe)

        if self.instance.pk:
            query = query.exclude(pk=self.instance.pk)

        if query.exists():
            raise ValidationError(_('Nazwa nie jest unikalna.'))

        return name

    def save(self, commit=True):
        """Override the save method to add Caffe relation."""

        stencil = super(StencilForm, self).save(commit=False)
        stencil.caffe = self._caffe
        if commit:
            stencil.save()
            self.save_m2m()

        return stencil

caffe/stencils/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, redirect, render

from reports.forms import FullProductForm
from reports.models import Product, Report
from reports.views import get_report_categories

from .forms import StencilForm
from .models import Stencil


@permission_required('stencils.add_stencil')
def stencils_new_stencil(request):
    """Show form to create new stencil and show existing stencils."""

    form = StencilForm(request.POST or None, caffe=request.user.caffe)

    if form.is_valid():
        form.save()
        messages.success(request, 'Szablon został poprawnie dodany.')
        return redirect(reverse('reports:navigate'))

    stencils = Stencil.objects.filter(caffe=request.user.caffe).all()
    return render(request, 'stencils/new.html', {
        'form': form,
        'stencils': stencils
    })


@permission_required('stencils.change_stencil')
def stencils_edit_stencil(request, stencil_id):
    """Edit already existing stencil with stencil_id."""

    stencil = get_object_or_404(
        Stencil,
        id=stencil_id,
        caffe=request.user.caffe
    )

    form = StencilForm(
        request.POST or None,
        instance=stencil,
        caffe=stencil.caffe
    )

    if form.is_valid():
        form.save()
        messages.success(request, 'Szablon został poprawnie zmieniony.')
        return redirect(reverse('reports:navigate'))

    return render(request, 'stencils/edit.html', {
        'form': form,
        'stencil': stencil
    })


@permission_required('stencils.view_stencil')
def stencils_show_stencil(request, stencil_id):
    """Show stencil with stencil_id."""

    stencil = get_object_or_404(
        Stencil,
        id=stencil_id,
        caffe=request.user.caffe
    )

    categories = stencil.categories.all()

    return render(request, 'stencils/show.html', {
        'stencil': stencil,
        'categories': categories
    })


@permission_required('stencils.view_stencil')
def stencils_show_all_stencils(request):
    """Show all existing stencils."""

    stencils = Stencil.objects.filter(caffe=request.user.caffe).all()
    return render(request, 'stencils/all.html', {
        'stencils': stencils
    })


@permission_required('reports.add_report')
def stencils_new_report(request, stencil_id):
    """Create new report from given stencil.

    Validate if report is correct by FullProduct validation. Check if report
    is not empty.
    """

    checked = []
    all_categories = []

    stencil = get_object_or_404(
        Stencil,
        id=stencil_id,
        caffe=request.user.caffe
    )

    categories = stencil.categories.all()

    for category in categories:
        products = Product.objects.filter(category=category).all()

        all_products = []
        for product in products:
            all_products.append({
                'id': product.id,
                'name': product.name,
                'unit': product.unit.name
            })

        all_categories.append({
            'id': category.id,
            'name': category.name,
            'products': all_products
        })

    if request.POST:
        post = request.POST.copy()
        forms = []
        valid = True

        post.pop('csrfmiddlewaretoken', None)

        # check validation and create form for each fullproduct
        for full_product in post:
            fp_list = post.getlist(full_product)
            form = FullProductForm(
                {
                    'product': fp_list[0],
                    'amount': fp_list[1]
                },
                caffe=request.user.caffe
            )

            if not form.is_valid():
                valid = False

                checked.append({
                    'product': fp_list[0],
                    'amount': '',
                    'error': form.errors['amount']
                })
            else:
                checked.append({
                    'product': fp_list[0],
                    'amount': fp_list[1],
                    'error': ''
                })

            forms.append(form)

        # check if some form exists
        if len(forms) > 0 and valid:
            report = Report.objects.create(
                creator=request.user,
                caffe=request.user.caffe,
            )

            # for each form save it with its report
            for form in forms:
                full_product = form.save()
                full_product.report = report
                full_product.save()

            report.save()
            messages.success(request, 'Raport został poprawnie dodany.')
            return redirect(reverse('stencils:all'))
        else:
            messages.error(
                request,
                u'Formularz został niepoprawnie wypełniony.'
            )

    # get last five reports
    latest_reports = Report.objects.filter(caffe=request.user.caffe).all()[:5]
    for report in latest_reports:
        report.categories = get_report_categories(report.id)

    return render(request, 'stencils/new_report.html', {
        'stencil': stencil,
        'categories': all_categories,
        'checked': checked,
        'reports': latest_reports
    })

caffe/templates/stencils/all.html
{% extends "home/base.html" %}

{% block title %}
Szablony
{% endblock %}

{% block content %}
<section class="stencils">
  {% for stencil in stencils %}
    <div class="stencil">
      <div class="stencil__name">
        {{ stencil.name }}
      </div>

      <div class="stencil__description">
        {% if stencil.description %}
          {{ stencil.description }}
        {% endif %}
      </div>

      <div class="stencil__buttons">
        {% if perms.reports.add_report %}
          <a href="{% url 'stencils:new_report' stencil.id %}" class="button button-rounded button-green button-with-icon">
            <i class="fa fa-wpforms" aria-hidden="true"></i>
            <span>
              Nowy raport
            </span>
          </a>
        {% endif %}

        <a href="{% url 'stencils:show' stencil.id %}" class="button button-rounded button-blue button-with-icon">
          <i class="fa fa-search" aria-hidden="true"></i>
          <span>
            Pokaż szablon
          </span>
        </a>
      </div>
    </div>
  {% endfor %}
</sections>
{% endblock %}

caffe/templates/stencils/edit.html
{% extends "home/base.html" %}
{% load tags %}

{% block title %}
Edytuj szablon
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  <div class="input-line">
    {{ form.name }}
    {{ form.name.label_tag }}
  </div>
  {{ form.name.errors }}

  <div class="input-line">
    {{ form.description }}
    {{ form.description.label_tag }}
  </div>
  {{ form.description.errors }}

  <div class="input-line">
    {{ form.categories }}
    {{ form.categories.label_tag }}
  </div>
  {{ form.categories.errors }}

  <button type="submit" class="button button-rounded button-green">Uaktualnij</button>
  <button type="cancel" class="button button-rounded button-red">Anuluj</button>
</form>
{% endblock %}

caffe/templates/stencils/edit_stencil.html
{% extends "home/base.html" %}
{% load tags %}

{% block title %}
Edytuj szablon
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  <div class="input-line">
    {{ form.name }}
    {{ form.name.label_tag }}
  </div>
  {{ form.name.errors }}

  <div class="input-line">
    {{ form.description }}
    {{ form.description.label_tag }}
  </div>
  {{ form.description.errors }}

  <div class="input-line">
    {{ form.categories }}
    {{ form.categories.label_tag }}
  </div>
  {{ form.categories.errors }}

  <button type="submit" class="button button-rounded button-green">Uaktualnij</button>
  <button type="cancel" class="button button-rounded button-red">Anuluj</button>
</form>
{% endblock %}

caffe/templates/stencils/new.html
{% extends "home/base.html" %}

{% block title %}
  Nowy szablon
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  <div class="input-line">
    {{ form.name }}
    {{ form.name.label_tag }}
  </div>
  {{ form.name.errors }}

  <div class="input-line">
    {{ form.description }}
    {{ form.description.label_tag }}
  </div>
  {{ form.description.errors }}

  <div class="input-line">
    {{ form.categories }}
    {{ form.categories.label_tag }}
  </div>
  {{ form.categories.errors }}

  <button type="submit" class="button button-rounded button-green">Dodaj</button>
</form>

<h2 class="elements-subtitle">
  Już istniejące
</h2>

<ul class="elements">
  {% for stencil in stencils %}
    <li class="element">
      <span class="desc">
        {{ stencil.name }}
      </span>

      <a href="{{ stencil.show_href }}" class="button button-rounded button-small button-blue">
        Pokaż
      </a>

      {% if perms.stencils.change_stencil %}
        <a href="{{ stencil.edit_href }}" class="button button-rounded button-small button-red">
          Edytuj
        </a>
      {% endif %}
    </li>
  {% endfor %}
</ul>
{% endblock %}

caffe/templates/stencils/new_report.html
{% extends "home/base.html" %}

{% block title %}
Nowy raport
{% endblock %}

{% block content %}
<script type="text/javascript">
(function ($) {
  "use strict"

  var categories;
  var checked;

  function getProduct(product_id) {
    var product;

    for (var i = 0; i < categories.length; ++i) {
      for (var j = 0; j < categories[i].products.length; ++j) {
        if (product_id == categories[i].products[j]['id']) {
          product = categories[i].products[j];
        }
      }
    }

    return product;
  }


  $(document).ready(function() {
    categories = {{ categories|safe }};
    checked = {{ checked|safe }};
    //console.log(categories);

    $('.modaal').modaal();

    $('select').on('change', function(event, obj) {
      var category = $(this).closest('.category'); //.attr('id')
      var products = category.children('.products');

      var product = getProduct(this.value);
      if (product) {
        var errorClasses = '', amount = '', errors = '';

        if (obj) {
          if (obj.error) {
            // add error if error occured
            errors = '<ul class="errorlist"><li>' + obj.error + '</li></ul>';

            // change input border color if error occured
            errorClasses = 'error';
          }

          amount = obj.amount;
        }

        $(this).find(":selected").remove();

        products.append('\
          <div id="' + product.id + '" class="product">\
            <input type="hidden" name="' + product.id + '" value="' + product.id + '"/>\
            <div class="name">\
              ' + product.name +'\
            </div>\
            <div class="amount">\
              <input type="number" name="' + product.id + '" value="' + amount + '" class="' + errorClasses + '"/>\
            </div>\
            <div class="unit">\
              ' + product.unit + '\
            </div>\
            <div class="trash">\
              <i class="fa fa-trash-o" aria-hidden="true"></i>\
            </div>\
          </div>\
        ');

        products.append(errors);
      }
    });

    for (var k = 0; k < checked.length; ++k) {
      var p = getProduct(checked[k]['product']);

      $('select').find('#' + p.id).parent().val(p.id).trigger(
        'change',
        [{error:checked[k]['error'], amount:checked[k]['amount']}]
      );
    }

    $(document).on('click', '.trash', function() {
      var product = $(this).closest('.product');

      var p = getProduct(product.attr('id'));
      if (p) {
        var select = product.closest('.category').find('select');
        select.append('\
          <option id="' + p.id + '" value="' + p.id + '">' + p.name + '</option>\
        ');

        var errors = $(product).next('ul');
        if (errors) {
          errors.remove(); // remove error
        }
        product.remove();
      }
    });
  });
})(jQuery);
</script>

<section class="stencil-title">
  <div class="name">
    {{ stencil.name }}
  </div>

  {% if stencil.description %}
    <div class="description">
      {{ stencil.description }}
    </div>
  {% endif %}
</section>

<form method="POST" class="stencil-report-form">
  {% csrf_token %}

  <div class="categories">
    {% for category in categories %}
      <div id="{{ category.id }}" class="category">
        <div class="category-name">
          {{ category.name }}
        </div>
          <div class="select-product input-line">
            <div class="select-wrapper">
              <select>
                <option name="product" id="-1" value="-1">-------------</option>
                {% for product in category.products %}
                  <option name="product" id="{{ product.id }}" value="{{ product.id }}">{{ product.name }}</option>
                {% endfor %}
              </select>
            </div>
            <label for="">Wybierz produkt</label>
          </div>
        <div class="products">
        </div>
      </div>
    {% endfor %}
  </div>

  <button type="submit" class="button button-rounded button-green">Dodaj</button>
</form>

<section class="subtitle">
  Ostatnio utworzone
</section>

<section class="reports">
  {% for report in reports %}
    <div class="report">
      <a href="#modaal{{ report.id }}" class="modaal meta">
        {{ report.created_on }}
      </a>

      <a href="#modaal{{ report.id }}" class="modaal button button-rounded button-blue button-with-icon">
        <i class="fa fa-search" aria-hidden="true"></i>
        <span>
          Podglądaj
        </span>
      </a>

      <div id="modaal{{ report.id }}" class="hidden">
        <div class="modal-report">
          <section class="report-title">
            {{ report.created_on }}
          </section>

          <section class="categories">
            {% for category, products in report.categories.items %}
              <div class="category">
                <div class="category-name">
                  {{ category }}
                </div>
                <div class="products">
                  {% for product in products %}
                    <div class="product">
                      <div class="name">{{ product.name }}</div>
                      <div class="amount">{{ product.amount }}</div>
                      <div class="unit">{{ product.unit }}</div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
          </section>
        </div>
      </div>
    </div>
  {% endfor %}
</section>
{% endblock %}

caffe/templates/stencils/new_stencil.html
{% extends "home/base.html" %}

{% block title %}
  Nowy szablon
{% endblock %}

{% block content %}
<form method="POST" class="element-form">
  {% csrf_token %}

  <div class="input-line">
    {{ form.name }}
    {{ form.name.label_tag }}
  </div>
  {{ form.name.errors }}

  <div class="input-line">
    {{ form.description }}
    {{ form.description.label_tag }}
  </div>
  {{ form.description.errors }}

  <div class="input-line">
    {{ form.categories }}
    {{ form.categories.label_tag }}
  </div>
  {{ form.categories.errors }}

  <button type="submit" class="button button-rounded button-green">Dodaj</button>
</form>

<h2 class="elements-subtitle">
  Już istniejące
</h2>

<ul class="elements">
  {% for stencil in stencils %}
    <li class="element">
      <span class="desc">
        {{ stencil.desc }}
      </span>

      <a href="{{ stencil.show_href }}" class="button button-rounded button-small button-blue">
        Pokaż
      </a>

      {% if perms.stencils.change_stencil %}
        <a href="{{ stencil.edit_href }}" class="button button-rounded button-small button-red">
          Edytuj
        </a>
      {% endif %}
    </li>
  {% endfor %}
</ul>
{% endblock %}

caffe/templates/stencils/show.html
{% extends "home/base.html" %}

{% block title %}
Szablon
{% endblock %}

{% block content %}
<section>
  <div class="stencil__name">{{ stencil.name }}</div>

  {% if stencil.description %}
    <div class="stencil__description">{{ stencil.description }}</div>
  {% endif %}
</section>

{% if perms.stencils.change_stencil %}
  <section class="buttons">
    <a href="{% url 'stencils:edit' stencil.id %}" class="button button-rounded button-red">
      Edytuj
    </a>
  </section>
{% endif %}

<section class="categories">
  {% for category in categories %}
    <div class="category">
      <div class="category-name">
        {{ category }}
      </div>
    </div>
  {% endfor %}
</section>
{% endblock %}